from .datos_de_prueba import *
from .cliente import *
from .estadisticas import *
from .funciones_generales import *
from .login import *
from .menu_p import *
from .ventas import *
from .productos import *
from .recetas import *
